FROM ghcr.io/openwrt/buildbot/buildworker-v3.8.0:v9

COPY --chown=buildbot staging_dir /prebuilt_tools/staging_dir
COPY --chown=buildbot build_dir /prebuilt_tools/build_dir
COPY --chown=buildbot .toolchainhash /.toolchainhash
COPY --chown=buildbot .ccache /.ccache