name: Build and Push prebuilt tools container

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      repo_branch:
        required: true
        type: string
      target:
        required: true
        type: string
      subtarget:
        required: true
        type: string
      author:
        required: true
        type: string
      build_tools:
        type: boolean
      build_toolchain:
        type: boolean 
      build_prebuild_toolchain:
        type: boolean         

jobs:
  push-toolchain-container:
    name: Push Target Toolchain container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: abu9/actions-shared-workflows
          sparse-checkout: .github/dockerfiles/Dockerfile.toolchain
          ref: ${{ github.ref_name }}
          sparse-checkout-cone-mode: false

      - name: Download prebuild toolchain from build job
        if: inputs.build_prebuild_toolchain
        uses: actions/download-artifact@v4
        with:
          name: mediatek-filogic-prebuild-toolchain
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 9762986203

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push prebuild toolchain
        if: inputs.build_prebuild_toolchain
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/abu9/pre-toolchain:mediatek-filogic-immortalwrt_openwrt-23.05
          file: .github/dockerfiles/Dockerfile.toolchain
