name: Build Toolchains

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      repo_branch:
        required: true
        type: string
      target:
        required: true
        type: string
      subtarget:
        required: true
        type: string
      author:
        required: true
        type: string             
jobs:
  build:
    name: Build Target Toolchain
    permissions:
      contents: read
      packages: read
      actions: write
    # strategy:
    #    fail-fast: False
    #    matrix:
    #      include: ${{fromJson(needs.determine_targets.outputs.target)}}

    uses: ./.github/workflows/reusable_build.yml
    with:
      target: ${{ inputs.target }}
      subtarget: ${{ inputs.subtarget }}
      repo_url: ${{ inputs.repo_url }}
      repo_branch: ${{ inputs.repo_branch }}
      build_toolchain: true
      build_external_toolchain: true
      upload_external_toolchain: true
      author: ${{ inputs.author }}
